name: Daily Search Trigger

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to trigger endpoint
        run: |
          curl -X POST https://your-vercel-deployment-url.com/trigger \
               -H "Authorization: Bearer ${{ secrets.TRIGGER_TOKEN }}"