name: Update Alzheimers Feed

on:
  schedule:
    # Runs at the start of every hour
    - cron: '0 * * * *'

jobs:
  update_feed:
    runs-on: ubuntu-latest
    steps:
      - name: POST request to update feed
        uses: wei/curl@v1
        with:
          url: 'https://arewethereyet.info/update-feed'
          method: 'POST'
          contentType: 'application/json'
          data: '{"disease": "alzheimer"}'
